;; (define-key function-key-map "\e[11~" [f1])
;; (define-key function-key-map "\e[12~" [f2])
;; (define-key function-key-map "\e[13~" [f3])
;; (define-key function-key-map "\e[14~" [f4])
;; (define-key function-key-map "\e[15~" [f5])
;; (define-key function-key-map "\e[17~" [f6])
;; (define-key function-key-map "\e[18~" [f7])
;; (define-key function-key-map "\e[19~" [f8])
;; (define-key function-key-map "\e[20~" [f9])
;; (define-key function-key-map "\e[21~" [f10])
;; (define-key function-key-map "\e[23~" [f11])
;; (define-key function-key-map "\e[24~" [f12])

